#!/bin/bash

CMD=$1
shift

source $HOME/.config/minmon/minmonrc
source minmon-include

cleanup() {

	for pid in `ls $MINMON_TMP/lock* 2>/dev/null`; do
		pid=`cat $pid`
		(
		kill $pid 2> /dev/null
		sleep 3
		kill -9 $pid 2>/dev/null
		) &
	done
	rm -rf $MINMON_TMP

}

start() {

	$MINMON_HOME/minmond &

}

stop() {

	cleanup
	killall minmond 2> /dev/null
	sleep 1
	killall minmond -9 2> /dev/null

}

case $CMD in

	"start") start ;;

	"stop")	stop ;;

	"cleanup") cleanup ;;

	"restart")

		stop
		start

	;;

	"launch")

		$MINMON_HOME/minmon-start $@

	;;

	*)

		echo "Usage: minmon (start|stop|launch <command> <args>)"

	;;

esac
