#!/bin/bash

if [ "$1" = "-min" ]; then

	MINIMIZE="true"
	shift

fi

source $HOME/.config/minmon/minmonrc
source minmon-include

minmon_tmpname=`echo $MINMON_TMP | sed 's/\/$//' | sed 's/.*\///'`
minmon_fifoname=`echo $MINMON_FIFO | sed 's/.*\///'`

if [ ! -d "$MINMON_TMP" ]; then
	grep -q "$minmon_tmpname" <(inotifywait -qme create "${MINMON_TMP/$minmon_tmpname}")
	sleep 0.5
fi

if [ $? -ne 0 ]; then
	echo "Parent directory of MINMON_TMP does not exist!" > /dev/stderr
	exit 1
fi

if [ ! -p "$MINMON_FIFO" ]; then
	grep -q "$minmon_fifoname" <(inotifywait -qme create "$MINMON_TMP")
fi


if [ -f "$MINMON_FIFO_LOCK" ]; then
	inotifywait -qme delete "$MINMON_FIFO_LOCK"
fi

touch $MINMON_FIFO_LOCK

if [ $MINIMIZE ]; then
	echo "$$:min:$@" > $MINMON_FIFO
else
	echo "$$:$@" > $MINMON_FIFO
fi

if [ ! $VERBOSE ]; then
	exit 0
fi

minmon_outfifo $$ &

echo "Printing command output. Press key to stop at any time."
read

minmon_outfifo $$ del

exit 0
