#!/bin/bash

if [ "$1" = "-min" ]; then

	MINIMIZE="true"
	shift

fi

source $HOME/.minmonrc
source minmon-include

while [ ! -p $MINMON_FIFO ]; do sleep 1; done

while [ -f $MINMON_FIFO_LOCK ]; do sleep 1; done

touch $MINMON_FIFO_LOCK

if [ $MINIMIZE ]; then
	echo "$$:min:$@" > $MINMON_FIFO
else
	echo "$$:$@" > $MINMON_FIFO
fi

if [ ! $VERBOSE ]; then
	exit 0
fi

minmon_outfifo $$ &

echo "Printing command output. Press key to stop at any time."
read

minmon_outfifo $$ del

exit 0
